---
- name: install golang from brew
  homebrew: name=golang state=present
  when: ansible_distribution == 'MacOSX'

- name: add golang apt repository
  apt_repository: repo="{{ go_apt_repo }}" state=present
  when: ansible_distribution == 'Ubuntu'
- name: install golang from apt
  package: name=golang state=present
  when: ansible_distribution == 'Ubuntu'

- name: create go dev environment
  file: path={{ item }} state=directory
  with_items:
  - "{{ go_path }}"
  - "{{ go_path }}/bin"
  - "{{ go_path }}/pkg"
  - "{{ go_path }}/src"
