zsh_install_script_url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
zsh_install_script_dest: /tmp/oh-my-zsh-install.sh
zsh_fonts_url: https://github.com/jeremyFreeAgent/oh-my-zsh-powerline-theme
zsh_fonts_dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/oh-my-zsh-powerline-theme"
zsh_theme_src: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/oh-my-zsh-powerline-theme/powerline.zsh-theme"
zsh_theme_dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerline.zsh-theme"
zsh_plugins:
- git
- go
- docker
zsh_theme: powerline
zsh_theme_settings:
  POWERLINE_RIGHT_A: exit-status-on-fail
  POWERLINE_HIDE_USER_NAME: true
  POWERLINE_HIDE_HOST_NAME: true
  POWERLINE_PATH: short
  POWERLINE_GIT_CLEAN: 😎
  POWERLINE_GIT_DIRTY: 💩
  POWERLINE_GIT_UNTRACKED: 🐽
zsh_user_options: |
  # dev_home env var:
  export e={{ dev_home }}

  # GOLANG setup:
  export GOPATH={{ go_path }}
  export PATH=$GOPATH/bin:$PATH
