---
- name: install from brew
  homebrew: name=packer state=present
  when: ansible_distribution == 'MacOSX'

- name: download zip for Ubuntu
  get_url: url="{{ packer_url }}" dest="{{ packer_download_dest }}"
  when: ansible_distribution == 'Ubuntu'
- name: install unzip from apt
  package: name=unzip state=present
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'
- name: extract packer.zip
  unarchive: src="{{ packer_download_dest }}" dest="{{ packer_dest }}"
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'
