---
- name: install from brew cask
  homebrew_cask: name=java state=present
  when: ansible_distribution == 'MacOSX'

- name: install open-jdk from apt
  package: name=openjdk-8-jdk state=present
  when: ansible_distribution == 'Ubuntu'
