---
vim_plugins:
  vim-fugitive: https://github.com/tpope/vim-fugitive
  nerdtree:     https://github.com/scrooloose/nerdtree
  vim-airline:  https://github.com/bling/vim-airline
  vim-go:       https://github.com/fatih/vim-go
